fix: Make parsing ABI files from Etherscan "unerrorable"
Previously we assumed ABI files to be valid from Etherscan.
Etherface however aborted unexpectedly because it failed
to parse such an ABI file containing a typo in the
'function' keyword, i.e. 'functin'. The error message was:
```
Error: Failed to deserialize content, invalid ABI?
`unknown variant `functin`, expected one of `function`, `event`, `error`, `constructor`, `fallback`, `receive` at line 1 column 79`
```
This commit fixes the Etherscan scraper by explicitly checking
if `parser::from_abi` returned an Ok enum.